{
    "openapi": "3.0.3",
    "info": {
        "title": "Sumple Auth System",
        "description": "Simple Auth System",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:8080"
        }
    ],
    "paths": {
        "/api/signup": {
            "post": {
                "description": "Register new user",
                "requestBody":{
                    "content": {
                        "application/json": {
                            "schema":{
                                "type": "object",
                                "properties": {
                                    "email":{
                                        "type": "string"
                                    },
                                    "first_name":{
                                        "type": "string"
                                    },
                                    "middle_name":{
                                        "type": "string"
                                    },
                                    "last_name":{
                                        "type": "string"
                                    },
                                    "address":{
                                        "type": "string"
                                    },
                                    "gender":{
                                        "type": "string"
                                    },
                                    "married_status":{
                                        "type": "string"
                                    },
                                    "password":{
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "email", "first_name", "last_name", "address", "gender", "married_status", "password"
                                ]
                            },
                            "examples": {
                                "success":{
                                    "description": "Sign up user john doe",
                                    "value":{
                                        "email": "doe@mail.com",
                                        "first_name": "John",
                                        "middle_name": "",
                                        "last_name": "Doe",
                                        "address": "Circle Street, No.1, Bandung, West Java",
                                        "gender": "male",
                                        "married_status": "single",
                                        "password": "secret111"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201":{
                        "description": "Success register new user",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "description": {
                                                    "type": "string"
                                                },
                                                "error_message": {
                                                    "type": "string"
                                                },
                                                "execute_at": {
                                                    "type": "string"
                                                },
                                                "result": {
                                                    "type": "string"
                                                },
                                                "value": {
                                                    "type": "object",
                                                    "properties": {
                                                        "fullname":{
                                                            "type": "string"
                                                        },
                                                        "email":{
                                                            "type": "string"
                                                        },
                                                        "address":{
                                                            "type": "string"
                                                        },
                                                        "gender":{
                                                            "type": "string"
                                                        },
                                                        "married_status":{
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Success register new user",
                                        "value": {
                                            "description": "SignUp success",
                                            "error_message": "",
                                            "execute_at": "2024/09/22 19:45:05.469",
                                            "result": "success",
                                            "value": {
                                                "fullname": "John Doe",
                                                "email": "doe@mail.com",
                                                "address": "Circle Street, No.1, Bandung, West Java",
                                                "gender": "male",
                                                "marital_status": "single"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "description": {
                                                    "type": "array"
                                                },
                                                "error_message": {
                                                    "type": "string"
                                                },
                                                "execute_at": {
                                                    "type": "string"
                                                },
                                                "result": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }, 
                                "examples": {
                                    "validationerror": {
                                            "description": "Validation error",
                                            "value": {
                                                    "description": [
                                                        "FirstName is a required field",
                                                        "MaritalStatus must be one of [single married divorced]"
                                                    ],
                                                    "error_message": "Unprocessable Entity",
                                                    "execute_at": "2024/09/22 19:44:11.778",
                                                    "result": "failure"
                                            }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Client Error",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "description": {
                                                    "type": "string"
                                                },
                                                "error_message": {
                                                    "type": "string"
                                                },
                                                "execute_at": {
                                                    "type": "string"
                                                },
                                                "result": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }, 
                                "examples": {
                                    "duplicated email": {
                                            "description": "email is registered",
                                            "value": {
                                                "description": "email is registered",
                                                "error_message": "Conflict",
                                                "execute_at": "2024/09/22 19:45:18.494",
                                                "result": "failure"
                                            }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "Login user",
                "requestBody": {
                    "content": {
                        "application/json":{
                            "schema":{
                                "type": "object",
                                "properties": {
                                    "email":{
                                        "type": "string"
                                    },
                                    "password":{
                                        "type": "string"
                                    }
                                }
                            },
                            "examples": {
                                "success": {
                                    "description": "correct login parameter",
                                    "value":{
                                        "email": "doe@mail.com",
                                        "password": "secret111"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200":{
                        "description": "Success login",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "description": {
                                            "type": "string"
                                        },
                                        "error_message": {
                                            "type": "string"
                                        },
                                        "execute_at": {
                                            "type": "string"
                                        },
                                        "result": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "object",
                                            "properties": {
                                                "fullname":{
                                                    "type": "string"
                                                },
                                                "email":{
                                                    "type": "string"
                                                },
                                                "address":{
                                                    "type": "string"
                                                },
                                                "gender":{
                                                    "type": "string"
                                                },
                                                "married_status":{
                                                    "type": "string"
                                                },
                                                "access_token":{
                                                    "type": "string"
                                                },
                                                "refresh_token":{
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Success login",
                                        "value": {
                                            "description": "Login success",
                                            "error_message": "",
                                            "execute_at": "2024/09/23 16:49:26.806",
                                            "result": "success",
                                            "value": {
                                                "fullname": "John Doe",
                                                "email": "doe@mail.com",
                                                "address": "Circle Street, No.1, Bandung, West Java",
                                                "gender": "male",
                                                "marital_status": "single",
                                                "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                                                "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "description": {
                                                    "type": "string"
                                                },
                                                "error_message": {
                                                    "type": "string"
                                                },
                                                "execute_at": {
                                                    "type": "string"
                                                },
                                                "result": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }, 
                                "examples": {
                                    "wrong password": {
                                            "description": "wrong password",
                                            "value": {
                                                    "description": "your password is wrong",
                                                    "error_message": "Unauthorized",
                                                    "execute_at": "2024/09/22 19:44:11.778",
                                                    "result": "failure"
                                            }
                                    },
                                    "wrong email": {
                                            "description": "wrong email",
                                            "value": {
                                                    "description": "no user found with this email",
                                                    "error_message": "Unauthorized",
                                                    "execute_at": "2024/09/22 19:44:11.778",
                                                    "result": "failure"
                                            }
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "description": {
                                                    "type": "array"
                                                },
                                                "error_message": {
                                                    "type": "string"
                                                },
                                                "execute_at": {
                                                    "type": "string"
                                                },
                                                "result": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }, 
                                "examples": {
                                    "validationerror": {
                                            "description": "Validation error",
                                            "value": {
                                                    "description": [
                                                        "Email must be a valid email address"
                                                    ],
                                                    "error_message": "Unprocessable Entity",
                                                    "execute_at": "2024/09/22 19:44:11.778",
                                                    "result": "failure"
                                            }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/logout": {
            "post": {
                "description": "Logout user",
                "security": [
                    {
                        "bearerAuth":[]
                    }
                ],
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success log out user",
                        "content": {
                            "text/plain": {
                                "schema":{
                                    "type": "boolean"
                                },
                                "examples": {
                                   "success":{
                                    "value": "logout success"
                                   }
                                }
                            }
                        }
                    },
                    "401":{
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "description": {
                                                    "type": "string"
                                                },
                                                "error_message": {
                                                    "type": "string"
                                                },
                                                "execute_at": {
                                                    "type": "string"
                                                },
                                                "result": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Unauthorized":{
                                        "value": {
                                            "description": "token is blacklist",
                                            "error_message": "Unauthorized",
                                            "execute_at": "2024/09/22 19:44:11.778",
                                            "result": "failure"
                                        }
                                    },
                                    "empty auth header": {
                                        "description": "empty auth header",
                                        "value": {
                                            "description": [
                                                "no authorization header found"
                                            ],
                                            "error_message": "Unprocessable Entity",
                                            "execute_at": "2024/09/22 19:44:11.778",
                                            "result": "failure"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/email/verification":{
            "put": {
                "description": "verification an email",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success verifying the email",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "description": {
                                            "type": "string"
                                        },
                                        "error_message": {
                                            "type": "string"
                                        },
                                        "execute_at": {
                                            "type": "string"
                                        },
                                        "result": {
                                            "type": "string"
                                        },
                                        "value":{
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                            "description": "success",
                                            "value": {
                                                    "description": "Email is verified",
                                                    "error_message": "",
                                                    "execute_at": "2024/09/22 19:44:11.778",
                                                    "result": "success",
                                                    "value": ""
                                            }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "description": "failed to verify the email",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "description": {
                                            "type": "array"
                                        },
                                        "error_message": {
                                            "type": "string"
                                        },
                                        "execute_at": {
                                            "type": "string"
                                        },
                                        "result": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples": {
                                    "Unauthorizes":{
                                        "description": "expired token",
                                        "value":{
                                            "description": [
                                                "failed to parse token when verifying, err: token has invalid claims: token is expired"
                                            ],
                                            "error_message": "Unauthorized",
                                            "execute_at": "2024/10/06 17:25:21.993",
                                            "result": "failure"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/email/unverification":{
            "put": {
                "description": "unverification an email",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200":{
                        "description": "success delete user data",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "description": {
                                            "type": "string"
                                        },
                                        "error_message": {
                                            "type": "string"
                                        },
                                        "execute_at": {
                                            "type": "string"
                                        },
                                        "result": {
                                            "type": "string"
                                        },
                                        "value":{
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                            "description": "success",
                                            "value": {
                                                    "description": "user data is deleted",
                                                    "error_message": "",
                                                    "execute_at": "2024/09/22 19:44:11.778",
                                                    "result": "success",
                                                    "value": ""
                                            }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "description": "failed to delete user data",
                        "content": {
                            "application/json": {
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "description": {
                                            "type": "array"
                                        },
                                        "error_message": {
                                            "type": "string"
                                        },
                                        "execute_at": {
                                            "type": "string"
                                        },
                                        "result": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "examples": {
                                    "Unauthorizes":{
                                        "description": "expired token",
                                        "value":{
                                            "description": [
                                                "failed to parse token when verifying, err: token has invalid claims: token is expired"
                                            ],
                                            "error_message": "Unauthorized",
                                            "execute_at": "2024/10/06 17:25:21.993",
                                            "result": "failure"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/refresh_token":{
            "post": {
                "description": "renew refresh token",
                "requestBody": {
                    "content": {
                        "application/json":{
                            "schema":{
                                "type": "object",
                                "properties": {
                                    "data":{
                                        "type": "object",
                                        "properties": {
                                            "access_token":{
                                                "type": "string"
                                            },
                                            "refresh_token":{
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            },
                            "example":{
                                "valid":{
                                    "description": "valid request body",
                                    "value": {
                                        "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlMDcy...",
                                        "refresh_token": "4c489afa-485f-43f3-b5bc-23dd95b5a17a"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200":{
                        "description": "success renew refresh and access token",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "description": {
                                            "type": "string"
                                        },
                                        "error_message": {
                                            "type": "string"
                                        },
                                        "execute_at": {
                                            "type": "string"
                                        },
                                        "result": {
                                            "type": "string"
                                        },
                                        "value": {
                                            "type": "object",
                                            "properties": {
                                                "access_token":{
                                                    "type": "string"
                                                },
                                                "refresh_token":{
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                },
                                "example":{
                                    "success": {
                                        "description": "success renew refresh and access token",
                                        "value": {
                                            "description": "refresh token success",
                                            "error_message": "",
                                            "execute_at": "2024/10/30 22:46:04.684",
                                            "result": "success",
                                            "value": {
                                                "refresh_token": "4d1aeb5b-24a9-4dc9-bb39-c796e4d73e78",
                                                "access_token": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjlkODhkM2E0LTE5ZjAtNGMwNS1hODA0LWZiMmNmMDhlNWI5ZSIsInVzZXJfaWQiOjQyLCJpc3MiOiIiLCJuYW1lIjoiRHdpIFdhaHl1ZGkiLCJlbWFpbCI6ImR3aXdhaHl1ZGkxOTk2QGdtYWlsLmNvbSIsImFkZHJlc3MiOiJDaXJjbGUgU3RyZWV0LCBOby4xLCBCYW5kdW5nLCBXZXN0IEphdmEiLCJpYXQiOjE3MzAyOTU5NjQsImV4cCI6MTczMDI5NjI2NH0.GnmjRsP-rTuUnWZEXyEfJr8l62Uw5JxyuzOFp7ypfj8d4Tnl9VY4JU-d5AywwfSV8CdapK_xyT1pvR-ZgPZaAbMRP4t9P2zU3LWxJD03gE2nFIoHlH7zjeuxyV4fXXzt_u5tKiTkBuZRxEVNa43t-RE3SSfMqjW9sUrZUp3MYuuW2edeTTb_gg89T5Tg5zgaZn0h9HCNreWEXUlFNCYPEB3jymvsOZcO99pmrJpyCbCIvHhVXmGUBI_yekCjxLQ61GXNkg3Vw5o1VBuRmyd_o6IqvAOaOdlC3YFs9xV6YV8b8AiaTCJunO7tl4dUcz2bgyQEfWV3Sw6NECSjweppyw"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401":{
                        "description": "invalid refresh token",
                        "content": {
                            "application/json":{
                                "schema":{
                                    "type": "object",
                                    "properties": {
                                        "description": {
                                            "type": "string"
                                        },
                                        "error_message": {
                                            "type": "string"
                                        },
                                        "execute_at": {
                                            "type": "string"
                                        },
                                        "result": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "example":{
                                    "unauthorized": {
                                        "description": "invalid refresh token",
                                        "value": {
                                            "description": [
                                                "invalid refresh token, msg: failed to read refresh token, err: no rows in result set"
                                            ],
                                            "error_message": "Bad Request",
                                            "execute_at": "2024/10/30 22:47:38.331",
                                            "result": "failure"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}